import devsim
devsim.set_parameter(name="edge_couple_model", value='EdgeCouple')
devsim.set_parameter(name="edge_node0_volume_model", value='EdgeNodeVolume')
devsim.set_parameter(name="edge_node1_volume_model", value='EdgeNodeVolume')
devsim.set_parameter(name="element_edge_couple_model", value='ElementEdgeCouple')
devsim.set_parameter(name="element_node0_volume_model", value='ElementNodeVolume')
devsim.set_parameter(name="element_node1_volume_model", value='ElementNodeVolume')
devsim.set_parameter(name="node_volume_model", value='NodeVolume')
devsim.set_parameter(name="surface_area_model", value='SurfaceArea')
devsim.set_parameter(name="symbolic_iteration_limit", value=1)
devsim.set_parameter(device="mymos", name="body_bias", value=0.0)
devsim.set_parameter(device="mymos", name="drain_bias", value=0.0)
devsim.set_parameter(device="mymos", name="gate_bias", value=0.0)
devsim.set_parameter(device="mymos", name="source_bias", value=0.0)
devsim.set_parameter(device="mymos", region="bulk", name="ElectronCharge", value=1.6e-19)
devsim.set_parameter(device="mymos", region="bulk", name="Permittivity", value=9.8235e-13)
devsim.set_parameter(device="mymos", region="bulk", name="T", value=300)
devsim.set_parameter(device="mymos", region="bulk", name="V_t", value=0.025887193125000003)
devsim.set_parameter(device="mymos", region="bulk", name="kT", value=4.1419509e-21)
devsim.set_parameter(device="mymos", region="bulk", name="mu_n", value=400)
devsim.set_parameter(device="mymos", region="bulk", name="mu_p", value=200)
devsim.set_parameter(device="mymos", region="bulk", name="n1", value=10000000000.0)
devsim.set_parameter(device="mymos", region="bulk", name="n_i", value=10000000000.0)
devsim.set_parameter(device="mymos", region="bulk", name="p1", value=10000000000.0)
devsim.set_parameter(device="mymos", region="bulk", name="taun", value=1e-05)
devsim.set_parameter(device="mymos", region="bulk", name="taup", value=1e-05)
devsim.set_parameter(device="mymos", region="gate", name="ElectronCharge", value=1.6e-19)
devsim.set_parameter(device="mymos", region="gate", name="Permittivity", value=9.8235e-13)
devsim.set_parameter(device="mymos", region="gate", name="T", value=300)
devsim.set_parameter(device="mymos", region="gate", name="V_t", value=0.025887193125000003)
devsim.set_parameter(device="mymos", region="gate", name="kT", value=4.1419509e-21)
devsim.set_parameter(device="mymos", region="gate", name="mu_n", value=400)
devsim.set_parameter(device="mymos", region="gate", name="mu_p", value=200)
devsim.set_parameter(device="mymos", region="gate", name="n1", value=10000000000.0)
devsim.set_parameter(device="mymos", region="gate", name="n_i", value=10000000000.0)
devsim.set_parameter(device="mymos", region="gate", name="p1", value=10000000000.0)
devsim.set_parameter(device="mymos", region="gate", name="taun", value=1e-05)
devsim.set_parameter(device="mymos", region="gate", name="taup", value=1e-05)
devsim.set_parameter(device="mymos", region="oxide", name="ElectronCharge", value=1.6e-19)
devsim.set_parameter(device="mymos", region="oxide", name="Permittivity", value=3.4515e-13)
